apiVersion: v1
kind: Config
clusters:
- name: "aula"
  cluster:
    server: "https://rancher-weg.jac.bsb.br/k8s/clusters/c-5snpg"
- name: "aula-ip-172-31-82-90"
  cluster:
    server: "https://54.161.64.59:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURjeU1URXpNekl5TWxvWERUTXlNRGN4T0RFek16SXlNbG93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUwwbng2bDZBL090ClNibEhPK0I2V2NYUTNIMFhBMXBCUXFYWGFHcmRKTi9GVDRscjBpY2xXZ\
      FM1TGN6cGY0ayt4Z3NaR1dUU3FyTDQKL0FjZ3FuMFE0SG12ektJVE12S1J3aU53YXpuZERHRWJBM\
      E9JSXRyZnJGdFRvbGxRaitnU0dSSEU0aUFBTkcxSAo4R3hJVWJ1aElUZjhvd3dJbXJOUi9jWlVKQ\
      1FONVdlVnRHQmd6QnBmRGdXVUtVNENEN1Zoc1VyQmJUanpPUmFJClBvNHFDRlF6Mk5FYm1LZjduQ\
      m9GcTg1VlV5WWQzU0pzQWRsV2lSSnFzR2NrSHF6MDYxM2paWDdlLzU2b1RhdGMKY0pBOEFXZVRCQ\
      nFFR0Y5czNjUWg2ays3VXpkbnJqVTEvM3JTTUdMMkxHaGdtY04wdXI0VytWaTVIQWNVVVc5dApKT\
      0tOQXFNMW84a0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGSFhBQjlnczBwVTdmSlordTBkRllsekdKeXByTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQkRmMzBxUitKTDB0L3l0dEwrQ0x4ZklMUWNKdis0M0tFR2NuY\
      UVQNCtKdDN5MElaSS9zV2J2MjFHWAp3QnVoeVdPbWszdFptWVU0WlJQYVNIaG5pZUxUOHByNnlve\
      mlrL2twNG12eE1TbE9qK0dXUG9XdWtuWnppNFVzCnJvMTBKbzNFdU5Da0w1YjdVemh3di9oN05KM\
      WY2UTdsZVJOTDQ5aDEwamM5MWx5dTQzUFhUV2NrSW52Z2NBV2sKS1hsMDB1UW5oTnZYcGRwZERzT\
      Uk0OFhDSCtMM2pWWFVxNG8wbk1jQU1zY0FtYjk5ZDRBdk1vZks3cHJtSWlncQpPYVAvU25SNUFyd\
      HZtaFZSaThidEZZUlM1a2JmZUhUWkkwbkU3eEt4M3ZwVU1rNVFMR0pHd3hjSW5HZitSZVorCk1MR\
      Xo0VmtlYU9JOExES0tRajBJTUxTeExMSDEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
- name: "aula-ip-172-31-2-97"
  cluster:
    server: "https://52.73.115.55:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURjeU1URXpNekl5TWxvWERUTXlNRGN4T0RFek16SXlNbG93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUwwbng2bDZBL090ClNibEhPK0I2V2NYUTNIMFhBMXBCUXFYWGFHcmRKTi9GVDRscjBpY2xXZ\
      FM1TGN6cGY0ayt4Z3NaR1dUU3FyTDQKL0FjZ3FuMFE0SG12ektJVE12S1J3aU53YXpuZERHRWJBM\
      E9JSXRyZnJGdFRvbGxRaitnU0dSSEU0aUFBTkcxSAo4R3hJVWJ1aElUZjhvd3dJbXJOUi9jWlVKQ\
      1FONVdlVnRHQmd6QnBmRGdXVUtVNENEN1Zoc1VyQmJUanpPUmFJClBvNHFDRlF6Mk5FYm1LZjduQ\
      m9GcTg1VlV5WWQzU0pzQWRsV2lSSnFzR2NrSHF6MDYxM2paWDdlLzU2b1RhdGMKY0pBOEFXZVRCQ\
      nFFR0Y5czNjUWg2ays3VXpkbnJqVTEvM3JTTUdMMkxHaGdtY04wdXI0VytWaTVIQWNVVVc5dApKT\
      0tOQXFNMW84a0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGSFhBQjlnczBwVTdmSlordTBkRllsekdKeXByTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQkRmMzBxUitKTDB0L3l0dEwrQ0x4ZklMUWNKdis0M0tFR2NuY\
      UVQNCtKdDN5MElaSS9zV2J2MjFHWAp3QnVoeVdPbWszdFptWVU0WlJQYVNIaG5pZUxUOHByNnlve\
      mlrL2twNG12eE1TbE9qK0dXUG9XdWtuWnppNFVzCnJvMTBKbzNFdU5Da0w1YjdVemh3di9oN05KM\
      WY2UTdsZVJOTDQ5aDEwamM5MWx5dTQzUFhUV2NrSW52Z2NBV2sKS1hsMDB1UW5oTnZYcGRwZERzT\
      Uk0OFhDSCtMM2pWWFVxNG8wbk1jQU1zY0FtYjk5ZDRBdk1vZks3cHJtSWlncQpPYVAvU25SNUFyd\
      HZtaFZSaThidEZZUlM1a2JmZUhUWkkwbkU3eEt4M3ZwVU1rNVFMR0pHd3hjSW5HZitSZVorCk1MR\
      Xo0VmtlYU9JOExES0tRajBJTUxTeExMSDEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
- name: "aula-ip-172-31-3-232"
  cluster:
    server: "https://3.236.166.93:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURjeU1URXpNekl5TWxvWERUTXlNRGN4T0RFek16SXlNbG93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUwwbng2bDZBL090ClNibEhPK0I2V2NYUTNIMFhBMXBCUXFYWGFHcmRKTi9GVDRscjBpY2xXZ\
      FM1TGN6cGY0ayt4Z3NaR1dUU3FyTDQKL0FjZ3FuMFE0SG12ektJVE12S1J3aU53YXpuZERHRWJBM\
      E9JSXRyZnJGdFRvbGxRaitnU0dSSEU0aUFBTkcxSAo4R3hJVWJ1aElUZjhvd3dJbXJOUi9jWlVKQ\
      1FONVdlVnRHQmd6QnBmRGdXVUtVNENEN1Zoc1VyQmJUanpPUmFJClBvNHFDRlF6Mk5FYm1LZjduQ\
      m9GcTg1VlV5WWQzU0pzQWRsV2lSSnFzR2NrSHF6MDYxM2paWDdlLzU2b1RhdGMKY0pBOEFXZVRCQ\
      nFFR0Y5czNjUWg2ays3VXpkbnJqVTEvM3JTTUdMMkxHaGdtY04wdXI0VytWaTVIQWNVVVc5dApKT\
      0tOQXFNMW84a0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGSFhBQjlnczBwVTdmSlordTBkRllsekdKeXByTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQkRmMzBxUitKTDB0L3l0dEwrQ0x4ZklMUWNKdis0M0tFR2NuY\
      UVQNCtKdDN5MElaSS9zV2J2MjFHWAp3QnVoeVdPbWszdFptWVU0WlJQYVNIaG5pZUxUOHByNnlve\
      mlrL2twNG12eE1TbE9qK0dXUG9XdWtuWnppNFVzCnJvMTBKbzNFdU5Da0w1YjdVemh3di9oN05KM\
      WY2UTdsZVJOTDQ5aDEwamM5MWx5dTQzUFhUV2NrSW52Z2NBV2sKS1hsMDB1UW5oTnZYcGRwZERzT\
      Uk0OFhDSCtMM2pWWFVxNG8wbk1jQU1zY0FtYjk5ZDRBdk1vZks3cHJtSWlncQpPYVAvU25SNUFyd\
      HZtaFZSaThidEZZUlM1a2JmZUhUWkkwbkU3eEt4M3ZwVU1rNVFMR0pHd3hjSW5HZitSZVorCk1MR\
      Xo0VmtlYU9JOExES0tRajBJTUxTeExMSDEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "aula"
  user:
    token: "kubeconfig-u-sbhsnbhx48:crlgc2lb656smf7rn5h5qrq9w7dhjj689dq4d5w5pt54lqlfvk5ht5"


contexts:
- name: "aula"
  context:
    user: "aula"
    cluster: "aula"
- name: "aula-ip-172-31-82-90"
  context:
    user: "aula"
    cluster: "aula-ip-172-31-82-90"
- name: "aula-ip-172-31-2-97"
  context:
    user: "aula"
    cluster: "aula-ip-172-31-2-97"
- name: "aula-ip-172-31-3-232"
  context:
    user: "aula"
    cluster: "aula-ip-172-31-3-232"

current-context: "aula"
